### ISSUE TITLE
Icons aren't the same

### ISSUE THREAD

**Issue by CutzuSDS** [okarin001/Onepunch#2]
**Describe the bug**
Double library icon, sound timer is going under the app, shuffle/pause/loop is not in the good place, 

**Expected behavior**
The icons to look the same as in the example screenshots

**Screenshots**
https://i.imgur.com/YDeare5.png

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version I have no clue

**Comment by okarin001** [comment]
if you read the `README.md` i have mentioned that I removed the icons in v2(for now). Sorry, I couldn't change the screenshots. Those are of the older legacy UI. I'll do it soon.

And for the mini player issue. check this
```css
.main-nowPlayingBar-container {
  background-color: var(--spice-sec-player) !important;
  border-top: unset !important;

  height: 80px;
}
```
- in the `user.css` find the above section it'll be under _/* mini player edit */_ section
- remove the `height: 80px;` line
- save and reapply the theme.

see if this works.
